import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import MonacoEditor from "@monaco-editor/react";
import { Check, Code, Copy } from "lucide-react";
import React, { useState } from "react";

interface GeneratedCodeProps {
  generatedCode: string;
  setGeneratedCode: (code: string) => void;
  language: string;
  provider: string;
  model: string;
}

interface LanguageConfig {
  monaco: string;
  framework: string;
  badgeColor: string;
}

const languageConfigs: { [key: string]: LanguageConfig } = {
  javascript: {
    monaco: "javascript",
    framework: "Jest",
    badgeColor:
      "bg-yellow-100 text-yellow-800 hover:bg-yellow-200 dark:bg-yellow-900/20 dark:text-yellow-400 dark:hover:bg-yellow-900/30",
  },
  typescript: {
    monaco: "typescript",
    framework: "Jest",
    badgeColor:
      "bg-blue-100 text-blue-800 hover:bg-blue-200 dark:bg-blue-900/20 dark:text-blue-400 dark:hover:bg-blue-900/30",
  },
  python: {
    monaco: "python",
    framework: "pytest",
    badgeColor:
      "bg-blue-100 text-blue-800 hover:bg-blue-200 dark:bg-blue-900/20 dark:text-blue-400 dark:hover:bg-blue-900/30",
  },
  java: {
    monaco: "java",
    framework: "JUnit",
    badgeColor:
      "bg-red-100 text-red-800 hover:bg-red-200 dark:bg-red-900/20 dark:text-red-400 dark:hover:bg-red-900/30",
  },
  go: {
    monaco: "go",
    framework: "testing",
    badgeColor:
      "bg-cyan-100 text-cyan-800 hover:bg-cyan-200 dark:bg-cyan-900/20 dark:text-cyan-400 dark:hover:bg-cyan-900/30",
  },
  rust: {
    monaco: "rust",
    framework: "cargo test",
    badgeColor:
      "bg-orange-100 text-orange-800 hover:bg-orange-200 dark:bg-orange-900/20 dark:text-orange-400 dark:hover:bg-orange-900/30",
  },
};

const GeneratedCode: React.FC<GeneratedCodeProps> = ({
  generatedCode,
  setGeneratedCode,
  language,
  provider,
  model,
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  const config = languageConfigs[language] || languageConfigs.javascript;

  const handleCopy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(generatedCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy code:", err);
    }
  };

  return (
    <div className="h-[90vh] w-[35vw] bg-background border-l border-border shadow-lg transition-colors duration-300">
      <Card className="h-full rounded-none border-0 bg-card transition-colors duration-300">
        <CardHeader className="border-b border-border bg-muted/30 p-4 transition-colors duration-300">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-green-500/10 rounded-lg transition-colors duration-300">
                <Code className="h-5 w-5 text-green-600" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-foreground">
                  Generated Tests
                </h2>
                <p className="text-sm text-muted-foreground">
                  Generated by {provider} ({model})
                </p>
              </div>
            </div>
            <Badge
              variant="secondary"
              className={`${config.badgeColor} transition-colors duration-300`}
            >
              {config.framework}
            </Badge>
          </div>

          <div className="flex items-center gap-2 mt-4">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="gap-2 hover:bg-accent transition-colors duration-200"
            >
              {copied ? (
                <>
                  <Check className="h-4 w-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4" />
                  Copy Tests
                </>
              )}
            </Button>

            <div className="text-sm text-muted-foreground ml-2">
              {generatedCode.split("\n").length} lines • {generatedCode.length}{" "}
              chars
            </div>
          </div>
        </CardHeader>

        <CardContent className="flex-1 p-0 overflow-hidden">
          <div className="h-[60vh] p-4">
            <MonacoEditor
              height="100%"
              width="100%"
              language={config.monaco}
              value={generatedCode}
              onChange={(value) => setGeneratedCode(value || "")}
              theme="vs-dark"
              options={{
                fontSize: 14,
                minimap: { enabled: false },
                scrollBeyondLastLine: false,
                wordWrap: "on",
                fontFamily: "Fira Mono, monospace",
                automaticLayout: true,
                lineNumbers: "on",
                roundedSelection: false,
                scrollbar: {
                  vertical: "auto",
                  horizontal: "auto",
                },
                tabSize: 2,
                renderLineHighlight: "all",
                formatOnPaste: true,
                formatOnType: true,
                fixedOverflowWidgets: true,
                readOnly: false,
                placeholder:
                  "No tests generated yet, provide a code and click generate tests button",
              }}
            />
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default GeneratedCode;
